# 함수 모음

In [17]:
x = 3.1415
y = x * 3
z = [1, 2, 3, 4, 5]

print("x의 절댓값 : ", abs(x)) 
print("x의 소숫점 3째자리까지 : ", round(x, 3)) 
print("x, y 중 최댓값 : ", max(x, y))
print("x, y 중 최솟값 : ", min(x, y)) 
print("z의 합 : ", sum(z))
print("x^y : ", pow(x, y))
print("y를 x로 나눈 몫과 나머지 : ", divmod(y, x)) # y를 x로 나눈 몫과 나머지

ab = [True, True, False]
print("\n--- 내장함수 ---")
print("ab의 모든 요소가 참인지 검사 : ", all(ab))
print("ab의 하나 이상의 요소가 참인지 검사 : ", any(ab))

# 💡 객체 반환 함수들은 list()로 감싸서 출력하도록 수정
print("z의 모든 요소를 인덱스와 함께 반환 : ", list(enumerate(z, start=0)))
print("function의 조건을 만족하는 요소만 필터링 : ", list(filter(lambda v: v < 5, z)))
print("function을 요소 전체에 적용하여 변환 : ", list(map(lambda v: v * 2, z)))

# 💡 zip은 두 개 이상의 iterable을 묶을 때 사용하므로 변수 추가 및 list() 적용
z_letters = ['A', 'B', 'C', 'D', 'E']
print("여러 iterable의 요소를 병렬로 묶어서 반환 : ", list(zip(z, z_letters)))

x의 절댓값 :  3.1415
x의 소숫점 3째자리까지 :  3.142
x, y 중 최댓값 :  9.4245
x, y 중 최솟값 :  3.1415
z의 합 :  15
x^y :  48447.15292901259
y를 x로 나눈 몫과 나머지 :  (2.0, 3.1414999999999997)

--- 내장함수 ---
ab의 모든 요소가 참인지 검사 :  False
ab의 하나 이상의 요소가 참인지 검사 :  True
z의 모든 요소를 인덱스와 함께 반환 :  [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)]
function의 조건을 만족하는 요소만 필터링 :  [1, 2, 3, 4]
function을 요소 전체에 적용하여 변환 :  [2, 4, 6, 8, 10]
여러 iterable의 요소를 병렬로 묶어서 반환 :  [(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')]

In [19]:
# 판다스
# 데이터 프레일 컬럼 형 변환
import pandas as pd
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

In [26]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
df['year'] = df['year'].astype(str)
df['year'] = df['year'].astype(int)
df['year'] = df['year'].astype(float)
df['year'] = df['year'].astype(bool)
display(df)

    year  gender  지역코드    금액1    금액2
0   True       0   143  70713  43210
1   True       0   183  40306  39663
2   True       0   129  26646  41631
3   True       0   161  56843  12455
4   True       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  True       0   188  36641  13130
96  True       1   149  44584  24531
97  True       1   122  42745   6679
98  True       1   130  33093   8506
99  True       1   193  76105  18284

[100 rows x 5 columns]

In [31]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).sum())

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

             지역코드     금액1     금액2
year gender
2015 0        869  203174  121342
     1        877  302704  124087
2016 0       2347  823847  352305
     1        662  220960   65665
2017 0        759  177812  161578
     1        920  166964  119601
2018 0       2462  981033  424788
     1       1162  420219  202729
2019 0       1295  404251  245396
     1       1218  367999  160272
2020 0       1649  619067  318277
     1        930  339353  152693

In [32]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).mean())

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

                   지역코드           금액1           금액2
year gender
2015 0       173.800000  40634.800000  24268.400000
     1       146.166667  50450.666667  20681.166667
2016 0       156.466667  54923.133333  23487.000000
     1       165.500000  55240.000000  16416.250000
2017 0       151.800000  35562.400000  32315.600000
     1       153.333333  27827.333333  19933.500000
2018 0       144.823529  57707.823529  24987.529412
     1       145.250000  52527.375000  25341.125000
2019 0       161.875000  50531.375000  30674.500000
     1       135.333333  40888.777778  17808.000000
2020 0       149.909091  56278.818182  28934.272727
     1       155.000000  56558.833333  25448.833333

In [ ]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby 
display(df.groupby(by=['year','gender']).count()) # NaN 은 빼고 셈

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

             지역코드  금액1  금액2
year gender
2015 0          5    5    5
     1          6    6    6
2016 0         15   15   15
     1          4    4    4
2017 0          5    5    5
     1          6    6    6
2018 0         17   17   17
     1          8    8    8
2019 0          8    8    8
     1          9    9    9
2020 0         11   11   11
     1          6    6    6

In [ ]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).size()) # NaN 도 세어줌

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

year  gender
2015  0          5
      1          6
2016  0         15
      1          4
2017  0          5
      1          6
2018  0         17
      1          8
2019  0          8
      1          9
2020  0         11
      1          6
dtype: int64

In [35]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).max())

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

             지역코드    금액1    금액2
year gender
2015 0        197  71267  47675
     1        191  80271  38621
2016 0        196  92989  45941
     1        189  75726  24508
2017 0        161  82694  41631
     1        196  48360  33312
2018 0        188  96416  44734
     1        179  83744  39699
2019 0        196  96831  45864
     1        193  76235  27009
2020 0        196  80091  45111
     1        195  87505  44567

In [36]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).min())

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

             지역코드    금액1    금액2
year gender
2015 0        131  10301   8051
     1        101  22183   7368
2016 0        110  14499   5876
     1        123  22874   8343
2017 0        129  12869   5784
     1        101  12049  11655
2018 0        100  13420   7491
     1        110  12200   9495
2019 0        102  17400   9014
     1        100  15539   6679
2020 0        108  42635  12805
     1        101  28711   6081

In [37]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).std())

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

                  지역코드           금액1           금액2
year gender
2015 0       30.776614  24465.860218  16732.863243
     1       36.842457  20754.369551  13245.166098
2016 0       29.301065  27595.924880  13611.409390
     1       29.501412  23106.704669   6955.499425
2017 0       13.236314  28801.146979  15007.893416
     1       36.729643  13764.274186   7956.907307
2018 0       27.111426  27168.851228  12377.642294
     1       24.978562  24679.215610  11121.974137
2019 0       38.468679  27070.914212  13739.360195
     1       28.626910  25735.329864   7376.191344
2020 0       27.692795  12562.433258  10380.228688
     1       42.783174  26457.916293  15795.293557

In [38]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).var())

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

                    지역코드           금액1           금액2
year gender
2015 0        947.200000  5.985783e+08  2.799887e+08
     1       1357.366667  4.307439e+08  1.754344e+08
2016 0        858.552381  7.615351e+08  1.852705e+08
     1        870.333333  5.339198e+08  4.837897e+07
2017 0        175.200000  8.295061e+08  2.252369e+08
     1       1349.066667  1.894552e+08  6.331237e+07
2018 0        735.029412  7.381465e+08  1.532060e+08
     1        623.928571  6.090637e+08  1.236983e+08
2019 0       1479.839286  7.328344e+08  1.887700e+08
     1        819.500000  6.623072e+08  5.440820e+07
2020 0        766.890909  1.578147e+08  1.077491e+08
     1       1830.400000  7.000213e+08  2.494913e+08

In [39]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).median())

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

              지역코드      금액1      금액2
year gender
2015 0       195.0  32399.0  21896.0
     1       140.0  53410.5  17500.0
2016 0       161.0  53525.0  22019.0
     1       175.0  61180.0  16407.0
2017 0       155.0  26646.0  37097.0
     1       156.0  30335.0  19288.5
2018 0       143.0  58404.0  21964.0
     1       150.0  54949.0  23804.0
2019 0       178.5  48574.5  33484.5
     1       137.0  39855.0  18284.0
2020 0       152.0  55236.0  28944.0
     1       170.0  53618.5  22894.5

In [40]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).first())

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

             지역코드    금액1    금액2
year gender
2015 0        195  71267   9780
     1        150  22183  34592
2016 0        191  87371  16093
     1        123  22874  13716
2017 0        129  26646  41631
     1        188  12049  23070
2018 0        143  70713  43210
     1        126  71434  39177
2019 0        183  40306  39663
     1        100  39855  15729
2020 0        176  53016  32751
     1        101  31357  27386

In [41]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).last())

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

             지역코드    금액1    금액2
year gender
2015 0        151  10301  21896
     1        130  33093   8506
2016 0        110  16102  34375
     1        181  75726   8343
2017 0        153  13987  36289
     1        123  29738  12987
2018 0        188  36641  13130
     1        149  44584  24531
2019 0        102  28589  30945
     1        193  76105  18284
2020 0        132  55236  12805
     1        195  28711   6081

In [43]:
# 사용자 정의 함수
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
display(df.groupby(by=['year','gender']).apply(lambda x : x.sum()))

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

             지역코드     금액1     금액2
year gender
2015 0        869  203174  121342
     1        877  302704  124087
2016 0       2347  823847  352305
     1        662  220960   65665
2017 0        759  177812  161578
     1        920  166964  119601
2018 0       2462  981033  424788
     1       1162  420219  202729
2019 0       1295  404251  245396
     1       1218  367999  160272
2020 0       1649  619067  318277
     1        930  339353  152693

In [46]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(df)
# Groupby
# 여러 연산을 동시에
display(df.groupby(by=['year','gender']).agg(['sum','mean','count']))

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

             지역코드                       금액1                         금액2  \
              sum        mean count     sum          mean count     sum
year gender
2015 0        869  173.800000     5  203174  40634.800000     5  121342
     1        877  146.166667     6  302704  50450.666667     6  124087
2016 0       2347  156.466667    15  823847  54923.133333    15  352305
     1        662  165.500000     4  220960  55240.000000     4   65665
2017 0        759  151.800000     5  177812  35562.400000     5  161578
     1        920  153.333333     6  166964  27827.333333     6  119601
2018 0       2462  144.823529    17  981033  57707.823529    17  424788
     1       1162  145.250000     8  420219  52527.375000     8  202729
2019 0       1295  161.875000     8  404251  50531.375000     8  245396
     1       1218  135.333333     9  367999  40888.777778     9  160272
2020 0       1649  149.909091    11  619067  56278.818182    11  318277
     1        930  155.000000     6  339353  56558.833333     6  152693


                     mean count
year gender
2015 0       24268.400000     5
     1       20681.166667     6
2016 0       23487.000000    15
     1       16416.250000     4
2017 0       32315.600000     5
     1       19933.500000     6
2018 0       24987.529412    17
     1       25341.125000     8
2019 0       30674.500000     8
     1       17808.000000     9
2020 0       28934.272727    11
     1       25448.833333     6

In [49]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
# 데이터프레임 데이터 조작
display(df)
display(df.drop('지역코드',axis=1)) # 지역코드 열 삭제

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

    year  gender    금액1    금액2
0   2018       0  70713  43210
1   2019       0  40306  39663
2   2017       0  26646  41631
3   2019       0  56843  12455
4   2019       0  26371   9014
..   ...     ...    ...    ...
95  2018       0  36641  13130
96  2018       1  44584  24531
97  2019       1  42745   6679
98  2015       1  33093   8506
99  2019       1  76105  18284

[100 rows x 4 columns]

In [50]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
# 데이터프레임 데이터 조작
display(df)
display(df.drop(0, axis=0)) # 첫 번째 행 삭제

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

    year  gender  지역코드    금액1    금액2
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
5   2016       0   191  87371  16093
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[99 rows x 5 columns]

In [51]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
# 데이터프레임 데이터 조작
display(df)
display(df.rename(columns={'year':'연도','gender':'성별'})) # 컬럼명 변경

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

      연도  성별  지역코드    금액1    금액2
0   2018   0   143  70713  43210
1   2019   0   183  40306  39663
2   2017   0   129  26646  41631
3   2019   0   161  56843  12455
4   2019   0   174  26371   9014
..   ...  ..   ...    ...    ...
95  2018   0   188  36641  13130
96  2018   1   149  44584  24531
97  2019   1   122  42745   6679
98  2015   1   130  33093   8506
99  2019   1   193  76105  18284

[100 rows x 5 columns]

In [ ]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
# 데이터프레임 결합
display(df)