# Section 01 변수와 연산

In [3]:
# 파이썬에서 변수 선언 및 할당
number = 10
greeting = "안녕하세요!"

# 변수명 규칙
# 파이썬은 알파벳, 숫자, 밑줄로 구성하며, 숫자로 시작은 불가능하다.
# 파이썬은 대소문자를 구분한다.
# 파이썬의 예약어 (if, for, class 등)는 변수명으로 사용할 수 없다.
# 변수명은 그 용도나 저장된 데이터를 명확히 설명하는 이르믈 사용해야한다.

변수명 스타일
1. Snake_case : 모든 글자를 소문자로 하고 단어 사이에 밑줄 사용. 함수와 변수명에 주로 사용
2. CamelCase : 각 단어의 첫 글자를 대문자로 시작. 주로 클래스에 사용

In [2]:
# 연산자
# 변수할당
a, b = 10, 3.3 

# 기본 산술 연산자
print("a+b =", a+b)
print("a-b = ",a-b)
print("a*b = ",a*b)
print("a/b = ",a/b)
print("a%b (나눗셈 연산 후 나머지 계산) = ",a%b)
print("a//b (나눗셈의 몫을 정수로 반환) = ",a//b)
print("a**b = ",a**b)

a+b = 13.3
a-b =  6.7
a*b =  33.0
a/b =  3.0303030303030303
a%b (나눗셈 연산 후 나머지 계산) =  0.10000000000000053
a//b (나눗셈의 몫을 정수로 반환) =  3.0
a**b =  1995.2623149688789

In [4]:
# 비교 연산자
user_age=25
is_adult = user_age>=10
print("성인입니까?",is_adult)

성인입니까? True

In [6]:
# 논리연산자
a, b = True, False 

print("a and b", a and b)
print("a or b : ",a or b)
print("not a : ",not a)

a and b False
a or b :  True
not a :  False

# Section 02 데이터 타입의 이해

In [8]:
# 집합(Set) 형 데이터 타입 : 순서가 없고 중복된 요소를 허용하지 않는 컬렉션
# 수학적인 집합 연산을 지원하며, 주로 중복을 제거하거나 항목의 존재 여부를 빠르게 검사할 때 사용된다.

fruits = {'apple','banana','cherry','apple'}
print("Fruits set : ",fruits)

# 빈 집합 생성
empty_set = set()
print("Empty set : ",empty_set)

Fruits set :  {'cherry', 'banana', 'apple'}
Empty set :  set()

In [9]:
# 요소 추가
fruits.add('orange')
print("After adding orange:",fruits)

# 요소 삭제
fruits.remove('banana')
print("After deleting banana : ",fruits)

# 집합간 연산
other_fruits = {'berry','watermelon'}
union_fruits = fruits.union(other_fruits)
intersection_fruits = fruits.intersection(other_fruits)
print("Union of fruits:",union_fruits)
print("Intersection of fruits:",intersection_fruits)

After adding orange: {'cherry', 'orange', 'banana', 'apple'}
After deleting banana :  {'cherry', 'orange', 'apple'}
Union of fruits: {'watermelon', 'orange', 'berry', 'cherry', 'apple'}
Intersection of fruits: set()

In [10]:
# 논리형 데이터타입
p, q =  True, False
print(p, type(p))
print(q, type(q))
print(p+p)

True <class 'bool'>
False <class 'bool'>
2

In [11]:
is_active=True 
is_greater = 10>5 
is_equal= (10==5)

print("Is active : ",is_active)
print("Is greater : ",is_greater)
print("Is equal : ",is_equal)

Is active :  True
Is greater :  True
Is equal :  False

In [13]:
print("True and False : ",True and False)
print("True or False : ",True or False )
print("not True : ",not True )

True and False :  False
True or False :  True
not True :  False

In [14]:
a==3 
if (a==2) : print("a 는 2와 같습니다.")
else : print("a는 2와 같지 않습니다.")

a는 2와 같지 않습니다.

In [15]:
# 데이터 타입 변환 

# 숫자형 => 문자혈영
num=123
str_num = str(num)
print("문자열:",str_num,type(num))

# 문자혈 => 숫자형
num_again = float(str_num)
print("숫자형:",num_again, type(num_again))

# 리스트와 튜플 변환 
lst = [1,2,3]
print("리스트 : ",lst)
tup = tuple(lst)
print("튜플 : ",tup)

# 집합과 딕셔너리 
set_example = {'a', 'b', 'c'}
dic_from_set = {key: True for key in set_example}
print("Dictionary from set : ",dic_from_set)

문자열: 123 <class 'int'>
숫자형: 123.0 <class 'float'>
리스트 :  [1, 2, 3]
튜플 :  (1, 2, 3)
Dictionary from set :  {'a': True, 'b': True, 'c': True}

In [16]:
# 숫자를 논리형으로 변환
zero = 0
non_zero = 7 
bool_from_zero = bool(zero)
bool_from_nonzero = bool(non_zero  )
print("0을 논리형으로 바꾸면 : ",bool_from_zero)
print("7을 논리형으로 바꾸면 : ",bool_from_nonzero)

0을 논리형으로 바꾸면 :  False
7을 논리형으로 바꾸면 :  True

In [17]:
# 논리형을 숫자형으로 변환
true_bool = True 
false_bool =False 
int_from_true = int(true_bool)
int_from_false = int(false_bool)
print("True 는 숫자로 : ",int_from_true)
print("False 는 숫자로 : ",int_from_false)

True 는 숫자로 :  1
False 는 숫자로 :  0

In [18]:
# 논리형을 문자열로
str_from_true = str(true_bool)
str_from_false = str(false_bool)
print("True 는 문자열로 : ", str_from_true)
print("False 는 문자열로 : ",str_from_false)

True 는 문자열로 :  True
False 는 문자열로 :  False

In [19]:
# 문자열을 논리형으로
str_true, str_false = "True","False"
bool_from_str_true = bool(str_true)
bool_from_str_false = bool(str_false)
print(" 'True' 는 논리형으로 바꾸면 : ",bool_from_str_true)
print(" 'False' 는 논리형으로 바꾸면 : ",bool_from_str_false)

 'True' 는 논리형으로 바꾸면 :  True
 'False' 는 논리형으로 바꾸면 :  True

자료형별 메서드 요약
- str
    - upper(), lower(), replace(old, new), split(sep=None), join(iterable), strip(), istrip(), rstrip()
    - find(sub) : 부분 문자열 sub 를 찾아 처음 발견된 인덱스를 반환. 찾지 못하면 -1 을 반환
    - count(sub) : 부분 문자열 sub 가 문자열 내에 몇 번 등장하는지 횟수를 반환 
- list
    - append(item), insert(index, item), extend(iterable)
    - remove(item) : 리스트에서 첫 번째로 발견된 item 을 제거. 없으면 ValueError 발생
    - pop(index=-1) : 지정한 인덱스 위치의 요소를 제거하고, 그 요소를 반환. 기본값 (-1) 은 마지막 요소
    - clear()
    - index(item) : item 이 처음으로 나타내는 인덱스를 반환. 없으면 ValueError 발생 
    - count(item), sort(key=None, reverse=False), reverse(), copy()
- tuple
    - count(item), index(item)
- dictionary 
    - get(key[,defualt]) : key 에 대응하는 값 반환. key 가 없으면 default 를 반환하고, 기본값이 없으면 None 반환 
    - keys(), values()
    - items() : 키, 값 쌍 반환
    - update([other]) : 다른 딕셔너리(other) 의 키-값 쌍을 현재 딕셔너리에 병합
    - pop(key[, default])
    - popitem() : 마지막으로 추가된 (키, 값) 쌍을 꺼내고, 딕셔너리에서 삭제
    - setdefault(key[,defualt]) : key 가 이미 있으면 해당 값을 반환, 없으면 default 값을 키와 함께 딕셔너리에 추가한 후 그 값을 반환
    - clear()

# Section 03 Numpy 와 벡터

In [20]:
# 빈 배열 생성
import numpy as np 

x = np.empty(3)
print("빈 벡터 생성하기 : ",x)

# 배열 채우기
x[0] = 3
x[1] = 5
x[2] = 3
print("채워진 벡터 : ",x)

빈 벡터 생성하기 :  [3. 2. 1.]
채워진 벡터 :  [3. 5. 3.]

In [22]:
# 배열을 생성하면서 채우기
import numpy as np 

arr1 = np.arange(10)
print("Array from 0 to 9 : ",arr1)

Array from 0 to 9 :  [0 1 2 3 4 5 6 7 8 9]

In [23]:
arr2 = np.arange(0,2,0.5)
print(arr2)

[0.  0.5 1.  1.5]

In [25]:
repeated_vals = np.repeat(8,4)
print(repeated_vals)

[8 8 8 8]

In [26]:
repeated_array = np.repeat([1,2,4],3)
print(repeated_array)

[1 1 1 2 2 2 4 4 4]

In [27]:
repeated_each = np.repeat([1,2,4],repeats=[1,2,3])
print(repeated_each)

[1 2 2 4 4 4]

In [28]:
# 벡터 전체 반복
repeated_whole = np.tile([1,2,4],2)
print(repeated_whole)

[1 2 4 1 2 4]

In [30]:
# 벡터 슬라이싱

np.random.seed(42)
a = np.random.randint(1,21,10)
print(a)
print(a[1])

[ 7 20 15 11  8  7 19 11 11  4]
20

Indexing : 파이썬의 리스트, 튜플, 문자열 등의 데이터 구조에서 특정 요소에 접근하는 방법 

1. 인덱스는 0부터 시작 
2. 양의 인덱스는 앞에서부터, 음의 인덱스는 뒤에서부터 센다
3. 슬라이싱 구문 [start:stop:step] 에서 stop 은 포함되지 않는다.

In [ ]:
print(a[[0,2,4]])
print(np.delete(a,1)) # 두 번째 값 제외하고 추출

[ 7 15  8]
[ 7 15 11  8  7 19 11 11  4]

In [32]:
# 인덱싱 중복 선택
print(a)
print(a[[1,1,3,2]])

[ 7 20 15 11  8  7 19 11 11  4]
[20 20 11 15]

In [34]:
b = a[a>3]
print(b)

[ 7 20 15 11  8  7 19 11 11  4]

In [36]:
# 원하는 조건 값 추울
b = a[(a>2)&(a<9)]
print("2 ~ 9 사이 : ",b)

print("8만 : ",a[a==8])
print("8 아닌것만 : ",a[a!=8])

print("8 부정 : ",~(a==8))
print("a[~(a==8)]",a[~(a==8)])

b = a[np.arange(1,11)%2 == 1]
print("홀수만 : ",b)

2 ~ 9 사이 :  [7 8 7 4]
8만 :  [8]
8 아닌것만 :  [ 7 20 15 11  7 19 11 11  4]
8 부정 :  [ True  True  True  True False  True  True  True  True  True]
a[~(a==8)] [ 7 20 15 11  7 19 11 11  4]
홀수만 :  [ 7 15  8 19 11]

In [37]:
# 두 값이 모두 True 일때 True 반환
x = np.array([True, True, False])
y = np.array([True, False, False])
print(x & y)

[ True False False]

In [38]:
# Or 
print(x|y)

[ True  True False]

In [39]:
# 논리 연산자 혼합
import numpy as np

a = np.array([1,2,3,4,16,17,18])

result = a[(a==4)&(a>15)]
print(result)

[]

In [40]:
# 필터링을 이용한 벡터 변경
a = np.array([5, 10, 15, 20, 25, 30])

a[a>=10] = 10 
a

array([ 5, 10, 10, 10, 10, 10])

In [42]:
# 조건을 만족하는 위치 탐색 
a = np.array([1,5,7,8,10])

result = a<7
result

array([ True,  True, False, False, False])

In [43]:
result = np.where(a<7)
result

(array([0, 1]),)

In [45]:
# 통계
import numpy as np 
a = np.array([1,2,3,4,5])

print("sum",np.sum(a))
print("mean",np.mean(a))
print("medain",np.median(a))
print("std",np.std(a))

sum 15
mean 3.0
medain 3.0
std 1.4142135623730951

nan : 정의되지 않은 값이나 잘못된 값. 타입 float. 주로 데이터의 결측값을 나타냄.   
NaN : 값이 없음을 나타내는 특수한 상수. NoneType. 주로 변수 초기화, 함수 반환값, 조건문, 기본 인자값 등에 사용

In [46]:
# np.isnan() : 벡터 a의 원소가 nan인지 아닌지 알려주는 함수 
a = np.array([20, np.nan, 13, 24, 309])

a_filtered = a[~np.isnan(a)]
a_filtered

array([ 20.,  13.,  24., 309.])

In [ ]:
# 벡터 합치기 
str_vec = np.array(["사과","배","수박","참외"])
str_vec # <U2 : 최대 2글자의 유니코드

array(['사과', '배', '수박', '참외'], dtype='<U2')

In [48]:
mix_vec = np.array(["사과",12,"수박","참외"],dtype=str)
mix_vec

array(['사과', '12', '수박', '참외'], dtype='<U2')

In [49]:
# np.concatenate() : 벡터 묶기
combined_vec = np.concatenate((str_vec,mix_vec))
combined_vec

array(['사과', '배', '수박', '참외', '사과', '12', '수박', '참외'], dtype='<U2')

In [50]:
# np.column_stack() : 벡터 세로 붙이기
col_stacked = np.column_stack((np.arange(1,5), np.arange(12,16)))
col_stacked

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15]])

In [51]:
row_stacked = np.row_stack((np.arange(1,5),np.arange(12,16)))
row_stacked

array([[ 1,  2,  3,  4],
       [12, 13, 14, 15]])

In [ ]:
# np.resize : 벡터 길이 조정
uneven_stacked = np.column_stack((np.arange(1,5),np.arange(12,18)))
# 벡터 길이가 달라서 에러

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 6

In [54]:
vec1 = np.arange(1,5)
vec2 = np.arange(12,18)
vec1 = np.resize(vec1, len(vec2))
vec1

array([1, 2, 3, 4, 1, 2])

In [55]:
uneven_stacked = np.column_stack((vec1, vec2))
uneven_stacked

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 1, 16],
       [ 2, 17]])

1. 주어진 벡터의 각 요소에 5를 더한 새로운 벡터를 생성하시오

In [57]:
a = np.array([1,2,3,4,5])
print(a+5)

[ 6  7  8  9 10]

2. 주어진 벡터의 홀수 번째 요소만 추추하여 새로운 벡터를 생성하시오

In [60]:
a = np.array([12, 21, 35, 48, 5])
print(a[::2])

[12 35  5]

3. 주어진 벡터에서 최댓값을 찾으시오

In [61]:
a = np.array([1,22,93,64,54])
print(max(a))

93

4. 주어진 벡터에서 중복된 값을 제거한 새로운 벡터를 생성하시오

In [63]:
a = np.array([1,2,3,2,4,5,4,6])
print(np.unique(a))

[1 2 3 4 5 6]

5. 주어진 두 벡터 a, b 의 요소를 번갈아가며 위치시키는 새로운 벡터를 생성하시오

In [66]:
a = np.array([21, 31, 58])
b = np.array([24, 44, 67])
c = np.empty(a.size+b.size,dtype=a.dtype)

c[0::2] = a
c[1::2] = b 
print(c)

[21 24 31 44 58 67]

6. 다음 두 벡터 a와 b를 더한 결과를 구하시오

In [70]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9])
c = a[:-1]+b 
print(c)

[ 7  9 11 13]

# Section 04 Numpy 행렬과 배열

In [71]:
# 두 개의 벡터를 합쳐 행렬 생성
import numpy as np 
matrix = np.column_stack((np.arange(1,5),np.arange(12,16)))
print("행렬 : \n",matrix)
print("행렬의 크기 : ",matrix.shape)

행렬 :
 [[ 1 12]
 [ 2 13]
 [ 3 14]
 [ 4 15]]
행렬의 크기 :  (4, 2)

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

# cumprod() : 누적곱 반환
print("전체 누적곱 : ",a.cumprod())
print("열별 누적 곱 : \n",a.cumprod(axis=0))
print("행별 누적곱 : \n",a.cumprod(axis=1))

전체 누적곱 :  [  1   2   6  24 120 720]
열별 누적 곱 :
 [[ 1  2  3]
 [ 4 10 18]]
행별 누적곱 :
 [[  1   2   6]
 [  4  20 120]]

Numpy 배열의 기본 함수 
- sum()
- mean()
- max()
- min()
- std()
- var()
- cumsum()
- cumprod() : 배열 원소들의 누적곱
- argmax(axis = ) : 배열 원소들 중 최댓값. axis=0이면 행, 1이면 열
- argmin(axis = ) : 애별 원소들 중 최솟값, axis=0이면 행, 1이면 열 
- reshape(newshape) : 배열의 형상을 변경
- transpose() : 전치
- flatten() : 1차월 배열로 변환 
- clip(min, max) : 배열 원소들을 주어진 범위로 자름
- tolist() : 배열을 리스트로 변환
- astype(dtype) : 배열 원소들의 타입을 변환
- copy()
- sort()
- argsort() : 배열 원소들의 정렬된 인덱스를 반환

1. 다음과 같은 행렬 A 를 생성하시오   
행렬 A : 
[[3 5 7]
 [2 3 6]]

In [7]:
import numpy as np
A = np.array([[3, 5, 7], [2,3,6]])
print(A)

[[3 5 7]
 [2 3 6]]

2. 다음과 같이 행렬 B가 주어졌을 때, 2번째, 4번째, 5번째 행만을 선택하여 3 by 4 행렬을 생성하시오  
행렬 B :   
[[8 10 7 8]  
 [2 4 5 5 ]  
 [7 6 1 7 ]  
 [2 6 8 6 ]  
 [9 3 4 2 ]]

In [8]:
B = np.array([[8, 10, 7, 8], [2, 4, 5, 5],[7,6,1,7],[2,6,8,6],[9,3,4,2]])
B_2 = B[1]
B_4 = B[3]
B_5 = B[4]

C = [B_2,B_4,B_5]
print(C)

[array([2, 4, 5, 5]), array([2, 6, 8, 6]), array([9, 3, 4, 2])]

In [9]:
B = np.array([[8, 10, 7, 8], [2, 4, 5, 5],[7,6,1,7],[2,6,8,6],[9,3,4,2]])
B_selected = B[[1,3,4],:]
print("선택된 행렬 : \n",B_selected)

선택된 행렬 :
 [[2 4 5 5]
 [2 6 8 6]
 [9 3 4 2]]

3. 2번에서 주어진 행렬 B 에서 3번째 열의 값이 3보다 큰 행들만 골라내시오

In [10]:
B_filtered = B[B[:,2]>3,:]
print(B_filtered)

[[ 8 10  7  8]
 [ 2  4  5  5]
 [ 2  6  8  6]
 [ 9  3  4  2]]

# Scikit-learn 을 활용한 데이터 전처리

In [21]:
import pandas as pd 
import numpy as np 
df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/dat.csv')

X = df.drop(['grade'],axis=1)
y = df.grade

from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=0, shuffle=True, stratify=None)
# shuffle : 데이터 분할 전에 데이터 섞을지 여부

결측치 처리

In [14]:
# 평균 대치법
# 장점 : 쉽고 빠르게 결측치 대치 가능
# 단점 : 다른 변수 간의 상관관계를 고려하지 못함. 결측치가 많을 때 평균값의 빈도수가 많아지므로 분포가 왜곡
from sklearn.impute import SimpleImputer

train_X1 = train_X.copy()
test_X1 = test_X.copy()
# Strategy = 'mean' ==> 평균 대치법 적용.일변량 변수의 평균으로 결측치를 대치하는 방법  
imputer_mean = SimpleImputer(strategy='mean')

# goout 변수의 결측치를 평균으로 대치하고 저장
# fit_transform 은 데이터 학습 (fit) 하고, 데이터 변환한다. (transform)
train_X1['goout'] = imputer_mean.fit_transform(train_X1[['goout']])
test_X1['goout'] = imputer_mean.fit_transform(test_X1[['goout']])

print("학습 데이터 goout 변수 결측치 확인 : ",train_X1['goout'].isna().sum())
print("테스트 데이터 goout 변수 결측치 확+인 : ",test_X1['goout'].isna().sum())

학습 데이터 goout 변수 결측치 확인 :  0
테스트 데이터 goout 변수 결측치 확+인 :  0

In [16]:
# 중앙값 대치법
# 장점 : 쉽고 빠르게 결측치 대치 가능
# 단점 : 다른 변수 간의 관계를 고려하지 못함. 결측치가 많을 때 중앙값의 빈도수가 많아지므로 분포가 왜곡 

train_X2 = train_X.copy()
test_X2 = test_X.copy()

imputer_median = SimpleImputer(strategy='median')
train_X2['goout'] = imputer_median.fit_transform(train_X2[['goout']])
test_X2['goout'] = imputer_median.fit_transform(test_X2[['goout']])

print("학습 데이터 goout 변수 결측치 확인 : ",train_X2['goout'].isna().sum())
print("테스트 데이터 goout 변수 결측치 확인 : ",test_X2['goout'].isna().sum())

학습 데이터 goout 변수 결측치 확인 :  0
테스트 데이터 goout 변수 결측치 확인 :  0

In [19]:
# 최빈값 대치법
# 장점 : 쉽고 빠르게 결측치 대치 가능
# 단점 : 다른 변수 간의 상관관계를 고려하지 못함. 클래스 불균형을 심화시킬 수 있음. 

train_X3 = train_X.copy()
test_X3 = test_X.copy()

imputer_mode = SimpleImputer(strategy = 'most_frequent')
train_X3['goout'] = imputer_mode.fit_transform(train_X3[['goout']])
test_X3['goout'] = imputer_mode.fit_transform(test_X3[['goout']])

print("학습 데이터 goout 변수 결측치 확인 : ",train_X3['goout'].isna().sum())
print("테스트 데이터 goout 변수 결측치 확인 : ",test_X2['goout'].isna().sum())

학습 데이터 goout 변수 결측치 확인 :  0
테스트 데이터 goout 변수 결측치 확인 :  0

In [23]:
# KNN 방법. 이웃 관측치 정보 활용하여 결측치 대치
# 장점 : 데이터에 대한 가정 없이 쉽고 빠르게 결측치 대치
# 단점 : 변수 스케일 및 이상치에 민감하며, 고차원 데이터의 경우 모델 성능이 떨어질 수 있음.

from sklearn.impute import KNNImputer 
train_X5 = train_X.copy()
test_X5 = test_X.copy() 

# 수치형 칼럼만 선택
train_X5_num = train_X5.select_dtypes('number')
test_X5_num = test_X5.select_dtypes('number')

train_X5_cat = train_X5.select_dtypes('object')
test_X5_cat = test_X5.select_dtypes('object')

# 이웃의 크기가 5인 KNN 모형의 예측값을 이용
knnimputer = KNNImputer(n_neighbors=5)

train_X5_num_imputed = knnimputer.fit_transform(train_X5_num)
test_X5_num_imputed = knnimputer.fit_transform(test_X5_num)

# KNNImputer 는 np.array 로 출력되므로 데이터 프레임 형태로 변환
train_X5_num_imputed = pd.DataFrame(
    train_X5_num_imputed, columns=train_X5_num.columns, index=train_X5.index
)
test_X5_num_imputed = pd.DataFrame(
    test_X5_num_imputed, columns=test_X5_num.columns, index=test_X5.index
)

# 수치형 데이터와 범주형 데이터를 결합하여, 원 데이터 형태로 만듦 
train_X5 = pd.concat([train_X5_cat,train_X5_num_imputed],axis=1)
test_X5 = pd.concat([test_X5_cat,test_X5_num_imputed],axis=1)

print("학습 데이터 goout 변수 결측치 확인 : ",train_X5['goout'].isna().sum())
print("테스트 데이터 goout 변수 결측치 확인 : ",test_X5['goout'].isna().sum())

학습 데이터 goout 변수 결측치 확인 :  0
테스트 데이터 goout 변수 결측치 확인 :  0

In [34]:
# pandas 결측치 대치
data = {
    "학생" : ["철수","영희","민수","수지","지현"],
    "수학" : [85, np.nan, 78, np.nan, 93],
    "영어" : [np.nan, 88, 79, 85, np.nan],
    "과학" : [92, 85, np.nan, 80, 88]
}
df = pd.DataFrame(data)

In [35]:
# 평균값
df1 = df.copy()
display(df1)
df1 = df1.fillna(df1.mean(numeric_only=True))
display(df1)

   학생    수학    영어    과학
0  철수  85.0   NaN  92.0
1  영희   NaN  88.0  85.0
2  민수  78.0  79.0   NaN
3  수지   NaN  85.0  80.0
4  지현  93.0   NaN  88.0

   학생         수학    영어     과학
0  철수  85.000000  84.0  92.00
1  영희  85.333333  88.0  85.00
2  민수  78.000000  79.0  86.25
3  수지  85.333333  85.0  80.00
4  지현  93.000000  84.0  88.00

In [36]:
# 지정한 값으로 채우기
df2 = df.copy()
df2['수학'].fillna(0, inplace=True)
display(df2)

/var/folders/gw/jvr6w8xj12gc01xmg3zw29pw0000gn/T/ipykernel_31938/1194865972.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['수학'].fillna(0, inplace=True)

   학생    수학    영어    과학
0  철수  85.0   NaN  92.0
1  영희   0.0  88.0  85.0
2  민수  78.0  79.0   NaN
3  수지   0.0  85.0  80.0
4  지현  93.0   NaN  88.0

In [37]:
# 모든 결측치를 지정한 값으로 채우기
df2_1 = df.copy()
df2_1.fillna(50, inplace=True)
print(df2_1)

   학생    수학    영어    과학
0  철수  85.0  50.0  92.0
1  영희  50.0  88.0  85.0
2  민수  78.0  79.0  50.0
3  수지  50.0  85.0  80.0
4  지현  93.0  50.0  88.0

In [38]:
# 앞의 값으로 결측치 채우기
df2['영어'].fillna(method='ffill',inplace=True)
print(df2)

   학생    수학    영어    과학
0  철수  85.0   NaN  92.0
1  영희   0.0  88.0  85.0
2  민수  78.0  79.0   NaN
3  수지   0.0  85.0  80.0
4  지현  93.0  85.0  88.0

/var/folders/gw/jvr6w8xj12gc01xmg3zw29pw0000gn/T/ipykernel_31938/1758908548.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['영어'].fillna(method='ffill',inplace=True)
/var/folders/gw/jvr6w8xj12gc01xmg3zw29pw0000gn/T/ipykernel_31938/1758908548.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['영어'].fillna(method='ffill',inplace=True)

In [39]:
# 뒤의 값
df2['과학'].fillna(method='bfill',inplace=True)
print(df2)

   학생    수학    영어    과학
0  철수  85.0   NaN  92.0
1  영희   0.0  88.0  85.0
2  민수  78.0  79.0  80.0
3  수지   0.0  85.0  80.0
4  지현  93.0  85.0  88.0

/var/folders/gw/jvr6w8xj12gc01xmg3zw29pw0000gn/T/ipykernel_31938/4114122940.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['과학'].fillna(method='bfill',inplace=True)
/var/folders/gw/jvr6w8xj12gc01xmg3zw29pw0000gn/T/ipykernel_31938/4114122940.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['과학'].fillna(method='bfill',inplace=True)

In [41]:
# 다른 칼럼의 값 사용
df3 = df.copy()
display(df)
df3['수학'].fillna(df3['영어'],inplace=True)
display(df3)

   학생    수학    영어    과학
0  철수  85.0   NaN  92.0
1  영희   NaN  88.0  85.0
2  민수  78.0  79.0   NaN
3  수지   NaN  85.0  80.0
4  지현  93.0   NaN  88.0

/var/folders/gw/jvr6w8xj12gc01xmg3zw29pw0000gn/T/ipykernel_31938/617048820.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3['수학'].fillna(df3['영어'],inplace=True)

   학생    수학    영어    과학
0  철수  85.0   NaN  92.0
1  영희  88.0  88.0  85.0
2  민수  78.0  79.0   NaN
3  수지  85.0  85.0  80.0
4  지현  93.0   NaN  88.0

In [ ]:
#