# Python 기초와 데이터 구조

## 기출문제 제 9회

### 작업형 제 1유형

1. 각 연도 및 성별의 총 대출액의 절댓값 차이를 구하고, 절댓값 차이가 가장 큰 지역코드를 구하시오

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

raw_data = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_1.csv")
display(raw_data)

pd.set_option('display.max_columns',None) # 모든 칼럼이 출력되게 조절

raw_data['총대출액'] = raw_data['금액1'] + raw_data['금액2']
# 각 연도 및 성별로 총 대출액 합계 계산
dfgender = raw_data.groupby(['year','gender','지역코드'])['총대출액'].sum().reset_index()
display(dfgender)
# reset_index : 인덱스로 가버린 연도, 성별, 지역코드를 다시 일반 컬럼으로 끄집어내기

    year  gender  지역코드    금액1    금액2
0   2018       0   143  70713  43210
1   2019       0   183  40306  39663
2   2017       0   129  26646  41631
3   2019       0   161  56843  12455
4   2019       0   174  26371   9014
..   ...     ...   ...    ...    ...
95  2018       0   188  36641  13130
96  2018       1   149  44584  24531
97  2019       1   122  42745   6679
98  2015       1   130  33093   8506
99  2019       1   193  76105  18284

[100 rows x 5 columns]

    year  gender  지역코드    총대출액
0   2015       0   131   37881
1   2015       0   151   32197
2   2015       0   195  161121
3   2015       0   197   93317
4   2015       1   101   87088
..   ...     ...   ...     ...
89  2020       1   102  105908
90  2020       1   168   85313
91  2020       1   172   97854
92  2020       1   192  109436
93  2020       1   195   34792

[94 rows x 4 columns]

In [2]:
# 각 연도 및 성별에 따른 차이를 계산하기 위해 피벗 테이블 생성
df_pivot = dfgender.pivot_table(index= ['year','지역코드'], columns='gender',values='총대출액',fill_value=0)
display(df_pivot)
# index : 표의 맨 왼쪽 '행' 자리에 올 기준 정함 
# columns : 표의 열 자리에 펼쳐질 기준을 정함
# values : 행과 열이 만나는 교차에 채워넣을 진짜 데이터 값
# fill_value = 0 : 만약 특정 연도/ 지역에 특정 성별의 데이터가 없어서 결측치가 생기면 0으로 채워라.

# groupby 는 결과를 위에서 아래로 길게 보여주고, pivot_table은 데이터를 가로와 세로 양방향으로 쫙 펼쳐줌

gender           0         1
year 지역코드
2015 101       0.0   87088.0
     118       0.0  100609.0
     130       0.0   41599.0
     131   37881.0       0.0
     150       0.0   56775.0
...            ...       ...
2020 176   85767.0       0.0
     178   71066.0       0.0
     192       0.0  109436.0
     195       0.0   34792.0
     196   76900.0       0.0

[91 rows x 2 columns]

In [3]:
# 성별에 따른 절댓값 차이를 계산하고, 차이가 가장 큰 지역 코드를 출력
df_pivot['abs_diff'] = abs(df_pivot[0]-df_pivot[1])

max_diff = df_pivot['abs_diff'].idxmax()

max_diff_region = max_diff[1]

print("차이가 가장 큰 지역코드 : ",max_diff_region)
display(df_pivot)

차이가 가장 큰 지역코드 :  143

gender           0         1  abs_diff
year 지역코드
2015 101       0.0   87088.0   87088.0
     118       0.0  100609.0  100609.0
     130       0.0   41599.0   41599.0
     131   37881.0       0.0   37881.0
     150       0.0   56775.0   56775.0
...            ...       ...       ...
2020 176   85767.0       0.0   85767.0
     178   71066.0       0.0   71066.0
     192       0.0  109436.0  109436.0
     195       0.0   34792.0   34792.0
     196   76900.0       0.0   76900.0

[91 rows x 3 columns]

2. 각 연도별 최대 검거율을 가진 범죄유형을 찾아서 해당 연도 및 유형의 검거건수들의 총합을 구하시오  
(검거율 = 검거건수/발생건수)

In [4]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_2.csv")
display(df)

,연도,구분,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
0,2000,발생건수,302,635,470,306,271,900,220,814,321,666
1,2000,검거건수,302,430,470,187,271,199,220,230,321,408
2,2001,발생건수,969,543,691,613,585,391,476,360,659,513
3,2001,검거건수,121,352,691,613,574,158,476,360,575,513
4,2002,발생건수,982,389,886,762,766,443,704,330,684,846
5,2002,검거건수,120,266,373,487,700,415,113,330,684,445
6,2003,발생건수,764,539,291,566,654,627,708,975,234,405
7,2003,검거건수,180,539,291,101,489,627,205,871,234,405
8,2004,발생건수,601,929,755,361,401,469,470,655,661,926
9,2004,검거건수,351,801,395,361,401,469,437,152,661,316
10,2005,발생건수,963,387,579,692,240,356,214,264,720,543
11,2005,검거건수,228,387,571,162,238,356,214,264,720,518
12,2006,발생건수,488,578,972,689,430,240,227,334,400,979
13,2006,검거건수,132,147,602,506,430,240,198,334,400,646
14,2007,발생건수,938,812,661,842,968,204,417,702,966,597
15,2007,검거건수,894,492,306,114,653,204,417,674,842,340
16,2008,발생건수,763,295,933,684,606,430,948,854,370,740
17,2008,검거건수,135,295,259,684,342,185,895,677,370,656
18,2009,발생건수,773,845,995,227,819,755,539,997,530,839
19,2009,검거건수,605,447,572,227,289,324,484,476,382,732
20,2010,발생건수,827,944,458,558,909,655,610,848,517,876
21,2010,검거건수,324,333,458,558,473,655,610,571,332,791
22,2011,발생건수,312,696,641,763,467,709,585,586,312,812
23,2011,검거건수,312,180,641,212,101,709,319,586,312,324
24,2012,발생건수,584,602,837,329,252,883,929,871,909,615
25,2012,검거건수,346,538,302,283,222,500,866,393,379,615
26,2013,발생건수,397,710,951,343,808,400,323,386,525,663
27,2013,검거건수,397,710,759,343,502,400,323,246,247,663
28,2014,발생건수,688,839,750,537,840,978,672,350,614,497
29,2014,검거건수,688,362,750,243,445,723,671,101,403,353
30,2015,발생건수,851,652,236,359,208,432,298,858,407,330
31,2015,검거건수,503,251,153,219,208,432,298,724,407,330
32,2016,발생건수,303,453,426,311,709,672,298,352,537,905
33,2016,검거건수,262,453,426,260,679,497,298,352,491,234
34,2017,발생건수,394,600,839,232,887,659,669,574,221,949
35,2017,검거건수,394,137,329,232,662,537,669,382,126,325
36,2018,발생건수,476,997,808,483,680,652,858,715,746,391
37,2018,검거건수,148,611,116,271,319,257,576,145,472,391
38,2019,발생건수,298,944,236,479,548,696,501,380,806,298
39,2019,검거건수,298,215,236,352,260,355,422,227,117,298
40,2020,발생건수,934,765,769,522,885,991,825,487,862,838
41,2020,검거건수,254,589,485,522,203,492,345,275,138,576
42,2021,발생건수,881,958,737,607,724,705,235,884,219,520
43,2021,검거건수,875,611,499,607,570,242,191,453,219,520
44,2022,발생건수,250,864,897,774,389,324,349,513,769,541
45,2022,검거건수,250,791,781,774,153,324,349,363,152,541
46,2023,발생건수,819,204,302,395,973,549,246,855,468,569
47,2023,검거건수,735,204,302,395,756,219,246,703,157,445
48,2024,발생건수,940,673,316,990,326,592,840,257,833,712
49,2024,검거건수,850,195,316,217,326,592,587,257,371,288

In [8]:
df1 = df[df["구분"]=="검거건수"].set_index("연도").drop(columns="구분")
df2 = df[df["구분"]=="발생건수"].set_index("연도").drop(columns="구분")

# 검거율 계산
dfratio = df1/df2
display(dfratio)

,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
연도,,,,,,,,,,
2000,1.000000,0.677165,1.000000,0.611111,1.000000,0.221111,1.000000,0.282555,1.000000,0.612613
2001,0.124871,0.648250,1.000000,1.000000,0.981197,0.404092,1.000000,1.000000,0.872534,1.000000
2002,0.122200,0.683805,0.420993,0.639108,0.913838,0.936795,0.160511,1.000000,1.000000,0.526005
2003,0.235602,1.000000,1.000000,0.178445,0.747706,1.000000,0.289548,0.893333,1.000000,1.000000
2004,0.584027,0.862217,0.523179,1.000000,1.000000,1.000000,0.929787,0.232061,1.000000,0.341253
2005,0.236760,1.000000,0.986183,0.234104,0.991667,1.000000,1.000000,1.000000,1.000000,0.953959
2006,0.270492,0.254325,0.619342,0.734398,1.000000,1.000000,0.872247,1.000000,1.000000,0.659857
2007,0.953092,0.605911,0.462935,0.135392,0.674587,1.000000,1.000000,0.960114,0.871636,0.569514
2008,0.176933,1.000000,0.277599,1.000000,0.564356,0.430233,0.944093,0.792740,1.000000,0.886486
2009,0.782665,0.528994,0.574874,1.000000,0.352869,0.429139,0.897959,0.477432,0.720755,0.872467
2010,0.391778,0.352754,1.000000,1.000000,0.520352,1.000000,1.000000,0.673349,0.642166,0.902968
2011,1.000000,0.258621,1.000000,0.277851,0.216274,1.000000,0.545299,1.000000,1.000000,0.399015
2012,0.592466,0.893688,0.360812,0.860182,0.880952,0.566251,0.932185,0.451206,0.416942,1.000000
2013,1.000000,1.000000,0.798107,1.000000,0.621287,1.000000,1.000000,0.637306,0.470476,1.000000
2014,1.000000,0.431466,1.000000,0.452514,0.529762,0.739264,0.998512,0.288571,0.656352,0.710262
2015,0.591069,0.384969,0.648305,0.610028,1.000000,1.000000,1.000000,0.843823,1.000000,1.000000
2016,0.864686,1.000000,1.000000,0.836013,0.957687,0.739583,1.000000,1.000000,0.914339,0.258564
2017,1.000000,0.228333,0.392133,1.000000,0.746336,0.814871,1.000000,0.665505,0.570136,0.342466
2018,0.310924,0.612839,0.143564,0.561077,0.469118,0.394172,0.671329,0.202797,0.632708,1.000000
2019,1.000000,0.227754,1.000000,0.734864,0.474453,0.510057,0.842315,0.597368,0.145161,1.000000
2020,0.271949,0.769935,0.630689,1.000000,0.229379,0.496468,0.418182,0.564682,0.160093,0.687351
2021,0.993190,0.637787,0.677069,1.000000,0.787293,0.343262,0.812766,0.512443,1.000000,1.000000
2022,1.000000,0.915509,0.870680,1.000000,0.393316,1.000000,1.000000,0.707602,0.197659,1.000000
2023,0.897436,1.000000,1.000000,1.000000,0.776978,0.398907,1.000000,0.822222,0.335470,0.782074
2024,0.904255,0.289747,1.000000,0.219192,1.000000,1.000000,0.698810,1.000000,0.445378,0.404494

In [11]:
# 각 연도별 최대 검거율을 가진 범죄유형 산출
dfmax = dfratio.idxmax(axis=1)
dfmax_reset = dfmax.reset_index().rename({0: '범죄유형'},axis=1)
display(dfmax_reset)

      연도    범죄유형
0   2000   범죄유형1
1   2001   범죄유형3
2   2002   범죄유형8
3   2003   범죄유형2
4   2004   범죄유형4
5   2005   범죄유형2
6   2006   범죄유형5
7   2007   범죄유형6
8   2008   범죄유형2
9   2009   범죄유형4
10  2010   범죄유형3
11  2011   범죄유형1
12  2012  범죄유형10
13  2013   범죄유형1
14  2014   범죄유형1
15  2015   범죄유형5
16  2016   범죄유형2
17  2017   범죄유형1
18  2018  범죄유형10
19  2019   범죄유형1
20  2020   범죄유형4
21  2021   범죄유형4
22  2022   범죄유형1
23  2023   범죄유형2
24  2024   범죄유형3

In [13]:
# 각 연도별 범죄유형에 해당하는 검거건수의 총합을 출력
df1_melt = df1.reset_index().melt(id_vars="연도",var_name="범죄유형",value_name="검거건수")
display(df1_melt)
# melt : 가로로 뚱뚱하게 옆으로 펼져져 있는 표를 녹여서 아래로 길게 늘어뜨리는 역할
# id_vars = : 식별자로 사용할 컬럼. 녹이지 않고 그대로 고정해 둘 기준 컬럼
# var_name : 가로로 펼쳐져 있던 컬럼 이름들이 세로로 합쳐지며 들어갈 새로운 컬럼의 이름 
# value_name : 표 안에 진짜 숫자 데이터들이 모딜 새로운 컬럼의 이름

       연도    범죄유형  검거건수
0    2000   범죄유형1   302
1    2001   범죄유형1   121
2    2002   범죄유형1   120
3    2003   범죄유형1   180
4    2004   범죄유형1   351
..    ...     ...   ...
245  2020  범죄유형10   576
246  2021  범죄유형10   520
247  2022  범죄유형10   541
248  2023  범죄유형10   445
249  2024  범죄유형10   288

[250 rows x 3 columns]

In [ ]:
dffinal = pd.merge(dfmax_reset, df1_melt, on = ["연도","범죄유형"], how='left')
display(dffinal)
# pd.merge : 두 개의 서로 다른 데이터프레임을 특정 기준을 가지고 하나로 합치는 힘수. 엑셀의 VLOOKUP 이나 SQL 의 JOIN 역할 
# dfmax_reset : 병합의 기준이 되는 데이터프레임
# df1_melt : 붙이고 싶은 추가 정보를 가지고 있는 데이터프레임
# on : 두 표를 합칠 때 사용할 공통된 연결고리. 
# how : 왼쪽 데이터를 주인공으로 삼겠다는 뜻

      연도    범죄유형  검거건수
0   2000   범죄유형1   302
1   2001   범죄유형3   691
2   2002   범죄유형8   330
3   2003   범죄유형2   539
4   2004   범죄유형4   361
5   2005   범죄유형2   387
6   2006   범죄유형5   430
7   2007   범죄유형6   204
8   2008   범죄유형2   295
9   2009   범죄유형4   227
10  2010   범죄유형3   458
11  2011   범죄유형1   312
12  2012  범죄유형10   615
13  2013   범죄유형1   397
14  2014   범죄유형1   688
15  2015   범죄유형5   208
16  2016   범죄유형2   453
17  2017   범죄유형1   394
18  2018  범죄유형10   391
19  2019   범죄유형1   298
20  2020   범죄유형4   522
21  2021   범죄유형4   607
22  2022   범죄유형1   250
23  2023   범죄유형2   204
24  2024   범죄유형3   316

In [15]:
total_sum = dffinal['검거건수'].sum()
print("총 검거건수 합계 =",total_sum)

총 검거건수 합계 = 9879

3. 제시된 문제를 순서대로 풀고, 해답을 제시하시오

In [16]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_1_3.csv")

결측치 처리 : 결측치는 평균만족도 컬럼의 전체 평균으로 채우시오  
근속연수 : 결측치는 각 부서와 등급별 평균 근속연수로 채우시오. (평균값의 소수점은 버림 처리)

In [17]:
display(df)

           부서 등급     평균만족도  근속연수  교육참가횟수
0     Finance  C  4.023911  17.0     8.0
1   Marketing  A  3.756698  14.0    16.0
2          IT  B  2.628697  21.0    13.0
3   Marketing  A  3.196616   NaN    18.0
4   Marketing  C  4.770665  28.0    10.0
..        ... ..       ...   ...     ...
95         IT  A  4.884821  13.0     3.0
96  Marketing  A  4.787161  20.0    16.0
97      Sales  A  3.425397  15.0     4.0
98      Sales  A       NaN   3.0    18.0
99         HR  C  4.820796   NaN    17.0

[100 rows x 5 columns]

In [23]:
# 결측치 확인
df.isna().sum()

부서         0
등급         0
평균만족도     10
근속연수      10
교육참가횟수     0
dtype: int64

In [24]:
# 평균만족도 칼럼은 해당 칼럼의 평균으로 대치
df["평균만족도"] = df["평균만족도"].fillna(df["평균만족도"].mean())

In [25]:
# 부서와 등급에 따라 평균 근속연수로 대치
mean_tenure = (
    df.groupby(["부서","등급"])["근속연수"]
    .mean()
    .apply(np.floor)
    .reset_index()
    .rename(columns={"근속연수":"평균근속연수"})
)

In [26]:
# merge 로 결측치 대치
df = df.merge(mean_tenure, on = ["부서","등급"],how="left")
df["근속연수"] = np.where(
    df["근속연수"].isnull(), # 조건 : 근속연수가 결측치인 경우
    df["평균근속연수"], # 결측치일때 대치값
    df["근속연수"] # 결측치가 아닐 때 기존 값 유지
)

df.drop(columns=["평균근속연수"],inplace=True)

In [27]:
display(df)

           부서 등급     평균만족도  근속연수  교육참가횟수
0     Finance  C  4.023911  17.0     8.0
1   Marketing  A  3.756698  14.0    16.0
2          IT  B  2.628697  21.0    13.0
3   Marketing  A  3.196616  19.0    18.0
4   Marketing  C  4.770665  28.0    10.0
..        ... ..       ...   ...     ...
95         IT  A  4.884821  13.0     3.0
96  Marketing  A  4.787161  20.0    16.0
97      Sales  A  3.425397  15.0     4.0
98      Sales  A  3.756996   3.0    18.0
99         HR  C  4.820796  12.0    17.0

[100 rows x 5 columns]

(1) 부서가 'HR' 이고 등급이 'A' 인 사람들의 평균 근속연수를 계산하시오

In [30]:
A = df.loc[(df["부서"]=="HR")&(df["등급"]=="A"),"근속연수"].mean()
print(A)

17.625

(2) 부서가 Sales 이고 등급이 B 인 사람들의 평균 교육 참가 횟수

In [32]:
B = df.loc[(df["부서"]=="Sales")&(df["등급"]=="B"),"교육참가횟수"].mean()
print(B)

7.6

(3) 두 조건의 합

In [33]:
print(A+B)

25.225

### 작업형 제 2 유형

훈련 데이터로 학습한 모델을 테스트 데이터에 적용하여 예측한 결과를 제출하시오  
(Target : 농업 유형 (다중분류, {0,1,2}))  
제출 형식은 ID, pred 두 칼럼만 존재해야한다.

In [35]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_2_train.csv")
df2 = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_2_test.csv")
display(df)

        ID  지역 등급   농업면적    연도  라벨
0     2089  부산  B  27406  2010   0
1     1964  대전  C  50520  2006   0
2     1820  울산  B  15030  2021   0
3     1408  부산  A  65007  2019   0
4      205  충남  A  72526  2018   0
...    ...  .. ..    ...   ...  ..
1675  2394  서울  C  13852  2001   0
1676  1507  전북  A  91420  2019   0
1677   663  서울  B  64713  2008   0
1678   909  광주  A  23990  2003   0
1679   483  경남  C  92790  2006   0

[1680 rows x 6 columns]

In [36]:
import pandas as pd 
import numpy as np

train = df 
test = df2

In [37]:
# 데이터 탐색 
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1680 entries, 0 to 1679
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      1680 non-null   int64
 1   지역      1680 non-null   object
 2   등급      1680 non-null   object
 3   농업면적    1680 non-null   int64
 4   연도      1680 non-null   int64
 5   라벨      1680 non-null   int64
dtypes: int64(4), object(2)
memory usage: 78.9+ KB
None

In [38]:
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      720 non-null    int64
 1   지역      720 non-null    object
 2   등급      720 non-null    object
 3   농업면적    720 non-null    int64
 4   연도      720 non-null    int64
 5   라벨      720 non-null    int64
dtypes: int64(4), object(2)
memory usage: 33.9+ KB
None

In [39]:
# 테스트 데이터를 활용한 최종 결과를 제출하기 위해 ID 칼럼을 따로 저장한다. 
test_id = test['ID']
train_X = train.drop(['라벨'],axis=1)
train_y = train['라벨']

test_X = test.drop(['라벨'],axis=1)
test_y = test['라벨']

In [40]:
# 데이터 분할 
from sklearn.model_selection import train_test_split
train_X, valid_X, train_y, valid_y = train_test_split(train_X, train_y, test_size=0.3, random_state=1)

In [41]:
# 데이터 전처리
cat_columns = train_X.select_dtypes('object').columns.to_list()
# num_columns = train_X.select_dtypes('number').columns.to_list()

In [42]:
# one-hot incoding
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

train_X_preprocessed = onehotencoder.fit_transform(train_X[cat_columns])
valid_X_preprocessed = onehotencoder.transform(valid_X[cat_columns])
test_X_preprocessed = onehotencoder.transform(test_X[cat_columns])

# 모델 적합
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=1)
rf.fit(train_X_preprocessed,train_y)

# 모형 성능 확인
from sklearn.metrics import f1_score
pred_val = rf.predict(valid_X_preprocessed)
print('valid f1-macro:',f1_score(valid_y, pred_val, average='macro'))

valid f1-macro: 0.3099787685774947

In [43]:
# 테스트 데이터 활용한 최종 예측
test_pred = rf.predict(test_X_preprocessed)
test_pred = pd.DataFrame(test_pred, columns=['pred'])

In [44]:
# ID, pred 칼럼만 존재하는 결과 파일 생성
result = pd.concat([test_id, test_pred], axis=1)
print(result.head(2))

     ID  pred
0  1094     0
1  1341     0

In [45]:
# 최종 결과 저장
result.to_csv('9_2_result.csv', index=False) # 시험에서 제시되는 파일명 작성할 것

In [46]:
# 모델 성능이 낮으면 교차 검증을 활용한 하이퍼파라미터 튜닝을 진행 
train_X_full = np.concatenate([train_X_preprocessed, valid_X_preprocessed],axis=0)
train_y_full = np.concatenate([train_y, valid_y], axis=0)

In [47]:
# GridSearchCGV 를 통해 하이퍼파라미터 튜닝 진행
from sklearn.model_selection import GridSearchCV

param_grid = {'max_depth': [10, 20, 30],
              'min_samples_split' : [2, 5, 10]}

rf = RandomForestClassifier(random_state=1)
rf_search = GridSearchCV(estimator = rf,
                         param_grid = param_grid, 
                         cv = 3,
                         scoring = 'f1_macro')

rf_search.fit(train_X_full, train_y_full)
GridSearchCV(cv=3, estimator = RandomForestClassifier(random_state=1),
             param_grid={'max_depth': [10, 20, 30],
                         'min_samples_split' : [2, 5, 10]},
                         scoring = 'f1_macro')

print("교차검증 MAE-score:", rf_search.best_score_)

교차검증 MAE-score: 0.3111111111111111

In [48]:
# 하이퍼파라미터 튜닝 결과를 바탕으로 테스트 데이터 활용하여 최종 예측 
test_pred2 = rf_search.predict(test_X_preprocessed)
test_pred2 = pd.DataFrame(test_pred2, columns=['pred'])

In [50]:
# 테스트 데이터로 예측 
result = pd.concat([test_id, test_pred2],axis=1)

# 최종 결과 저장
result.to_csv('9_2_result.csv', index=False)

### 작업형 제 3 유형

평균만족도 : 결측치는 평균만족도 컬럼의 전체 평균으로 채우시오  
근속연수 : 결측치는 각 부서와 등급별 평균 근속연수로 채우시오 (평균값의 소수점은 버림 처리)

(1) 한 제조 회사에서 생산성을 높이고자 직원들의 주요 생산성 요인을 분석하기로 결정했다. 이를 위해 200 명의 직원 데이터를 수집했으며, 직원들의 근무 기간, 특성 정보, 그리고 개인적인 속성을 조사했다.

In [ ]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_3_1.csv")
display(df.info())
# f2 ~ f5 : 고객의 2 ~ 5 번째ㅣ 속ㄷ성
# design : 생산성 점수

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      200 non-null    int64
 1   tenure  200 non-null    int64
 2   f2      200 non-null    float64
 3   f3      200 non-null    int64
 4   f4      200 non-null    float64
 5   f5      200 non-null    float64
 6   design  200 non-null    float64
dtypes: float64(4), int64(3)
memory usage: 11.1 KB

None

In [53]:
display(df.isnull().sum())

id        0
tenure    0
f2        0
f3        0
f4        0
f5        0
design    0
dtype: int64

모든 칼럼을 활용하여 design 을 예측하는 다중회귀 분석을 시행한 후 유의하지 않는 설명변수 개수를 구하시오. (패널티는 포함되지 않으며, 모델의 절편항은 포함)

In [ ]:
from sklearn.model_selection import train_test_split

훈련 데이터 (학습용 데이터)의 예측값과 실제값의 피어슨 상관계수를 구하시오

적합한 모델을 활용하여 테스트 데이터에서의 RMSE 를 구하시오

(2) 한 통신 회사에서는 고객 이탈을 줄이고자 주요 요인들을 분석하기로 결정하였다. 이를 위해 500 명이 고객 데이터를 수집했으며, 고객의 서비스 이용 및 가입 정보, 그리고 일부 개인적인 속성을 조사하였다.

In [ ]:
df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/9_3_2.csv")
display(df.info())
display(df.isnull().sum())
# col1, col2 : 고객의 1 ~ 2 번째 속성
# Phone_Service : 폰 서비스 가입 여부
# Tech_Insurande : 기술 보험 가입 여부 
# churn : 이탈 여부

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   col1            500 non-null    float64
 1   col2            500 non-null    float64
 2   Phone_Service   500 non-null    int64
 3   Tech_Insurance  500 non-null    int64
 4   churn           500 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 19.7 KB

None

col1              0
col2              0
Phone_Service     0
Tech_Insurance    0
churn             0
dtype: int64

고객 이탈을 예측하는 로지스틱 회귀를 시행한 후 col1 칼럼의 p-value 를 구하시오

폰 서비스를 받지 않은 고객 대비 받은 고객의 이탈 확률 오즈비를 구하시오

이탈할 확률이 0.3 이상인 고객 수를 구하시오