# 작업형 제1유형

1. 각 제품보고서별 처리 시간 (처리시각과 신고시각의 차이) 칼럼(초단위) 을  생성 후 공장별 처리 시간의 평균을 산출하시오. 산출된 결과를 바탕으로 평균 처리시간이 3번째로 적은 공장명을 구하시오

In [1]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_1_1.csv")
display(df.head(3))
print(len(df))

,제품보고서번호,공장명,결함유형,신고일자,신고시각,처리일자,처리시각,작업자직업명,사고발생장소
0,202200000001M25795,공장B,기계 결함,20220722,205914,20221027,184738,기술자,라인5
1,202200000002M10860,공장B,품질 문제,20220622,31050,20221109,132745,검사원,라인3
2,202200000003M86820,공장B,전기 결함,20220424,140320,20221130,35714,기술자,라인2

500

In [2]:
print(df.isnull().sum())

제품보고서번호    0
공장명        0
결함유형       0
신고일자       0
신고시각       0
처리일자       0
처리시각       0
작업자직업명     0
사고발생장소     0
dtype: int64

In [3]:
# 6자리가 안되는 노이즈행 골라내기
action_str = df['처리시각'].astype(str)
warning_str = df['신고시각'].astype(str)

# 글자수가 6자리 안되면 필터링
noise = (action_str.str.len() != 6) | (warning_str.str.len() != 6)
#display(df[noise])

In [4]:
# 공장별 처리시간의 평균
# 처리시간 = 처리시각 - 신고시각
df['처리시각'] = df['처리시각'].astype(str).str.zfill(6)
df['신고시각'] = df['신고시각'].astype(str).str.zfill(6)

df['처리시각'] = pd.to_datetime(df['처리시각'],format='%H%M%S')
df['신고시각'] = pd.to_datetime(df['신고시각'],format='%H%M%S')
df['처리시각-신고시각'] = df['처리시각']-df['신고시각']
df2 = df.groupby(['공장명'])['처리시각-신고시각'].mean().reset_index()
df2 = df.sort_values(['처리시각-신고시각'],ascending=True)

In [5]:
display(df2.head(5))
factory3 = df2.iloc[2]['공장명']
print(f"평균 처리시간이 3번째로 적은 공장명 : {factory3}")

,제품보고서번호,공장명,결함유형,신고일자,신고시각,처리일자,처리시각,작업자직업명,사고발생장소,처리시각-신고시각
136,202200000137M64268,공장E,안전 문제,20221205,1900-01-01 22:57:55,20220107,1900-01-01 00:10:15,관리자,라인5,-1 days +01:12:20
334,202200000335M64240,공장B,기계 결함,20220707,1900-01-01 23:11:09,20220101,1900-01-01 00:54:58,검사원,라인2,-1 days +01:43:49
209,202200000210M47157,공장E,전기 결함,20221218,1900-01-01 23:02:53,20220917,1900-01-01 01:28:47,기타,라인5,-1 days +02:25:54
160,202200000161M36105,공장D,품질 문제,20220216,1900-01-01 23:44:18,20220828,1900-01-01 02:13:37,검사원,라인5,-1 days +02:29:19
299,202200000300M27429,공장E,안전 문제,20220115,1900-01-01 23:48:18,20220707,1900-01-01 02:51:10,관리자,라인5,-1 days +03:02:52

평균 처리시간이 3번째로 적은 공장명 : 공장E

2. STATION_ADDR1 변수에서 구 정보만 추출한 후, 마포구, 성동구의 평균 이동거리를 구하시오

In [6]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_1_2.csv")
display(df.head(3))

,rent_date,rent_place,using_time,dist,bill_type,STATION_ADDR1,STATION_ID,STATION_LATITUDE,STATION_LONGITUDE
0,2019-03-19 00:42:26,ST-920,6,1660,BIL_002,서울특별시 구로구 경인로40길 47,ST-920,37.494995,126.858254
1,2019-02-14 10:53:40,ST-148,27,4530,BIL_004,서울특별시 중구 을지로 100,ST-148,37.565990,126.987793
2,2019-02-22 17:31:49,ST-10,28,4240,BIL_002,서울특별시 마포구 양화로 93,ST-10,37.552746,126.918617

In [7]:
df['지역구'] = df['STATION_ADDR1'].str.extract(r'([가-힣]+구)')
print(df['지역구'].unique())

<StringArray>
[ '구로구',   '중구',  '마포구',  '성동구',  '성북구',  '강서구', '영등포구',  '강남구',  '강동구',
  '종로구',  '송파구',    nan,  '광진구',  '동작구',  '강북구',  '노원구',  '관악구',  '양천구',
  '은평구',  '서초구',  '용산구',  '중랑구', '서대문구', '동대문구',  '금천구']
Length: 25, dtype: str

In [8]:
df['지역구'] = df['STATION_ADDR1'].str.split().str[1]
print(df['지역구'].unique())

['구로구' '중구' '마포구' '성동구' '성북구' '강서구' '영등포구' '강남구' '강동구' '종로구' '송파구' '면목동'
 '광진구' '동작구' '강북구' '노원구' '관악구' '양천구' '은평구' '서초구' '용산구' '중랑구' '서대문구' '녹번동'
 '동대문구' '금천구']

In [9]:
df['지역구'] = df['STATION_ADDR1'].str.extract(r'([가-힣]+구)')
df = df.dropna(subset=['지역구'])
display(df.head(3))

,rent_date,rent_place,using_time,dist,bill_type,STATION_ADDR1,STATION_ID,STATION_LATITUDE,STATION_LONGITUDE,지역구
0,2019-03-19 00:42:26,ST-920,6,1660,BIL_002,서울특별시 구로구 경인로40길 47,ST-920,37.494995,126.858254,구로구
1,2019-02-14 10:53:40,ST-148,27,4530,BIL_004,서울특별시 중구 을지로 100,ST-148,37.565990,126.987793,중구
2,2019-02-22 17:31:49,ST-10,28,4240,BIL_002,서울특별시 마포구 양화로 93,ST-10,37.552746,126.918617,마포구

In [10]:
# 마포구, 성동구의 평균 이동거리
df_mapo =  df[(df['지역구']=='마포구')]
df_sungdong=df[df['지역구']=='성동구']
print(f"마포구의 평균 이동거리 : {df_mapo['using_time'].mean()}")
print(f"성동구의 평균 이동거리 : {df_sungdong['using_time'].mean()}")

마포구의 평균 이동거리 : 28.529411764705884
성동구의 평균 이동거리 : 19.153846153846153

3. 분기별 총 판매량 (제품 A~E의 합계) 의 월평균을 구하고, 월평균이 최대인 연도와 분기를 구하시오

In [16]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_1_3.csv")
display(df.head(3))

         기간  제품A  제품B  제품C  제품D  제품E
0  2018년_1월  890  567  274  762  691
1  2018년_2월  270  831  930  539  393
2  2018년_3월  233  580  687  601  944

In [17]:
df['총판매량'] = df['제품A']+df['제품B']+df['제품C']+df['제품D']+df['제품E']
display(df.head(3))
df['월'] = df['기간'].str.split('_').str[1]

def get_quarter(month) :
    if month in ['1월','2월','3월']:
        return '1분기'
    elif month in ['4월','5월','6월']:
        return '2분기'
    elif month in ['7월','8월','9월']:
        return '3분기'
    else :
        return '4분기'
df['분기'] = df['월'].apply(get_quarter)
display(df.head(5))
# 분기별 총 판매량의 월평균
display(df.groupby(['분기'])['총판매량'].mean())

# 월평균이 최대인 연도와 분기 구하기
#df2 = df.groupby(['기간'])['총판매량'].mean()

         기간  제품A  제품B  제품C  제품D  제품E  총판매량
0  2018년_1월  890  567  274  762  691  3184
1  2018년_2월  270  831  930  539  393  2963
2  2018년_3월  233  580  687  601  944  3045

         기간  제품A  제품B  제품C  제품D  제품E  총판매량   월   분기
0  2018년_1월  890  567  274  762  691  3184  1월  1분기
1  2018년_2월  270  831  930  539  393  2963  2월  1분기
2  2018년_3월  233  580  687  601  944  3045  3월  1분기
3  2018년_4월  526  167  594  374  737  2398  4월  2분기
4  2018년_5월  124  913  213  949  442  2641  5월  2분기

분기
1분기    2989.000000
2분기    2041.166667
3분기    3172.500000
4분기    2707.500000
Name: 총판매량, dtype: float64

# 작업형 제2유형

훈련 데이터로 학습한 모델을 테스트 데이터에 적용하여 예측한 결과를 제출하시오 (분류 예측값 제출)
** 제출 형식은 ID, pred 두 칼럼만 존재해야한다. (평가지표 : macro f1-score)

In [18]:
import pandas as pd 

train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_2_test.csv")

display(train.head(3))

,level_0,ID,Marital Status,Application mode,Course,Daytime/evening attendance,Previous qualification,Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Educational special needs,Gender,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Target
0,0,3949,1_,43_,9147_,1_,1_,1_,1_,19_,9_,10_,0_,0_,0,5,9,5,Graduate
1,1,560,1_,53_,9003_,1_,42_,1_,3_,38_,141_,151_,0_,1_,7,12,18,11,Graduate
2,2,3186,1_,39_,9130_,1_,10_,1_,12_,36_,90_,90_,0_,1_,0,5,13,0,Dropout

In [19]:
# EDA
print("train data ")
print(train.isnull().sum())
print("test data ")
print(test.isnull().sum())

train data
level_0                                   0
ID                                        0
Marital Status                            0
Application mode                          0
Course                                    0
Daytime/evening attendance                0
Previous qualification                    0
Nacionality                               0
Mother's qualification                    0
Father's qualification                    0
Mother's occupation                       0
Father's occupation                       0
Educational special needs                 0
Gender                                    0
Curricular units 1st sem (credited)       0
Curricular units 1st sem (enrolled)       0
Curricular units 1st sem (evaluations)    0
Curricular units 1st sem (approved)       0
Target                                    0
dtype: int64
test data
level_0                                   0
ID                                        0
Marital Status                            0
Application mode                          0
Course                                    0
Daytime/evening attendance                0
Previous qualification                    0
Nacionality                               0
Mother's qualification                    0
Father's qualification                    0
Mother's occupation                       0
Father's occupation                       0
Educational special needs                 0
Gender                                    0
Curricular units 1st sem (credited)       0
Curricular units 1st sem (enrolled)       0
Curricular units 1st sem (evaluations)    0
Curricular units 1st sem (approved)       0
Target                                    0
dtype: int64

In [20]:
display(train.head(3))
display(test.head(3))

,level_0,ID,Marital Status,Application mode,Course,Daytime/evening attendance,Previous qualification,Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Educational special needs,Gender,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Target
0,0,3949,1_,43_,9147_,1_,1_,1_,1_,19_,9_,10_,0_,0_,0,5,9,5,Graduate
1,1,560,1_,53_,9003_,1_,42_,1_,3_,38_,141_,151_,0_,1_,7,12,18,11,Graduate
2,2,3186,1_,39_,9130_,1_,10_,1_,12_,36_,90_,90_,0_,1_,0,5,13,0,Dropout

,level_0,ID,Marital Status,Application mode,Course,Daytime/evening attendance,Previous qualification,Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Educational special needs,Gender,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Target
0,0,1903,1_,17_,9500_,1_,1_,1_,19_,1_,4_,10_,0_,0_,0,7,7,6,Graduate
1,1,796,1_,44_,9070_,1_,1_,1_,1_,1_,9_,8_,0_,0_,2,7,7,7,Graduate
2,2,1060,1_,53_,9238_,1_,42_,1_,1_,19_,5_,5_,0_,0_,5,9,12,7,Dropout

In [39]:
import pandas as pd 

train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_2_test.csv")

cat_cols = train.select_dtypes('object').columns.to_list()

if 'Target' in cat_cols:
    cat_cols.remove('Target')

for col in cat_cols:
    train[col] = train[col].astype(str).str.replace("_","",regex=False)
    test[col]= test[col].astype(str).str.replace("_","",regex=False)

train_X = train.drop(['Target'],axis=1)
train_X = train_X.astype(float)
test_X = test.drop(['Target'],axis=1)
test_X = test_X.astype(float)
train_y= train['Target']
test_y = test['Target']

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(train_X,train_y)

pred =rf.predict(test_X)

from sklearn.metrics import f1_score
print("macro f1 score : ",f1_score(test_y,pred,average='macro'))

id_cols = test['ID']

df_result = pd.DataFrame({'ID' : id_cols, 'pred' : pred})
display(df_result)

macro f1 score :  0.5444444444444444

C:\Users\user\AppData\Local\Temp\ipykernel_23204\1214023527.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = train.select_dtypes('object').columns.to_list()

       ID      pred
0    1903  Graduate
1     796  Graduate
2    1060  Graduate
3     791   Dropout
4    3416  Graduate
..    ...       ...
128  3887  Graduate
129   136  Graduate
130  4265  Graduate
131  2299   Dropout
132   133  Graduate

[133 rows x 2 columns]

# 작업형 제3유형

문제1 어느 학교에서 50명의 학생들을 대상으로 새로운 학습 프로그램의 효과를 조사하고자한다. 각 학생에 대해 학습 전과 학습 후의 시험 점수를 측정하였다.   


(1) 학습 전과 학습 후의 시험 점수의 평균과 표준편차를 구하시오 (소숫점 둘째 자리까지 반올림)  
(2) 학습 전후의 점수 차이가 유의미한지 검정하기 위해 대응표본 t-검정을 수행하고, 검정통계량을 계산하시오.  (소숫점 둘째 자리까지 반올림)  
(3) p-value를 바탕으로 유의수준 5%에서 귀무가설의 기각/채택 여부를 결정하시오. (p-value 는 소숫점 셋째 자리까지 반올림)

In [40]:
import pandas as pd 

df = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_3_1.csv")
display(df.head(3))

      before      after
0  87.640523  88.163191
1  74.001572  80.936085
2  79.787380  82.233354

In [42]:
# 학습 전과 학습 후의 시험점수의 평균과 표준편차
print(f"학습 전의 시험점수 평균은 {round(df['before'].mean(),2)} 이고 표준편차는 {round(df['before'].std(),2)} 입니다. ")
print(f"학습 후의 시험점수 평균은 {round(df['after'].mean(),2)} 이고 표준편차는 {round(df['after'].std(),2)} 입니다. ")

# 학습 점수 t-검정
from scipy import stats

st,pv = stats.ttest_rel(df['before'],df['after'])
print(f"학습 전후의 검정 통계량은 {round(st,2)} 입니다.")

# p_value 바탕
if pv < 0.05 : 
    print("귀무가설을 기각합니다.")
else :
    print("귀무가설을 채택합니다.")

학습 전의 시험점수 평균은 71.41 이고 표준편차는 11.37 입니다.
학습 후의 시험점수 평균은 76.3 이고 표준편차는 11.94 입니다.
학습 전후의 검정 통계량은 -7.9 입니다.
귀무가설을 기각합니다.

문제2 어느 회사가 조사한 고객 데이터는 100개의 샘플로 이루어져 있으며, 각 샘플에는 고객의 나이, 소득, 가족 수, 그리고 제품 구매 여부가 포함되어 있다. 로지스틱 회귀 분석을 통해 고객의 제품 구매 여부를 예측하고자 한다. (임계값 0.5 기준)  

(1) 로지스틱 회귀 분석을 수행하고, 소득 변수의 오즈비를 계산하시오.  
(2) train 데이터 기준의 잔차 이탈도 (Residual Deviance) 를 계산하시오.  
(3) test 데이터로 오분류율을 계산하시오.

In [44]:
import pandas as pd 

train = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_3_2_train.csv")
test = pd.read_csv(r"https://raw.githubusercontent.com/YoungjinBD/data/refs/heads/main/exam/7_3_2_test.csv")
display(train.head(3))

   age        income  family_members  purchase
0   37  43620.800179               2         0
1   56  60865.620200               3         1
2   21  39500.939224               2         0

In [53]:
from statsmodels.formula.api import logit 
formula = "purchase ~ age + income + family_members"
model = logit(formula, data=train).fit()

# 오즈비 계산
import numpy as np 
odds_ratio = np.exp(model.params['income'])
print(f"소득 변수의 오즈비 : {round(odds_ratio,2)}")

# train 데이터의 잔차 이탈도 계산
print(f"잔차이탈도 : {round(-2*model.llf,2)}")
#print(model.deviance)
#print(f"Deviance 이용해 잔차이탈도 계산하면 : {round(model.deviance,2)}")
# test 데이터로 오분류율 계산 
pred = model.predict(test)
pred_class = (pred>=0.5).astype(int)

misclassification_rate = np.mean(test['purchase']!= pred_class)
print(f" Test 데이터 기준 오분류율 : {round(misclassification_rate, 4)}")

Optimization terminated successfully.
         Current function value: 0.676174
         Iterations 4
소득 변수의 오즈비 : 1.0
잔차이탈도 : 108.19
 Test 데이터 기준 오분류율 : 0.35